In [1]:
import numpy as np

1. Create a single and multidimensional arrays using numpy and also create a array of numbers of a specified range.

In [2]:
x = np.arange(9)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
y = np.array([
    [1,2,3],
    [3,2,5]
])

In [5]:
y

array([[1, 2, 3],
       [3, 2, 5]])

2. Convert the above array to a 3 x 12 array.

In [6]:
x = np.arange(3 * 12)

In [7]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [8]:
x.shape = 3,12

In [9]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

3. Create a multidimentional square matrix and find the inverse of it.

In [10]:
x = np.array([
        [-3,2,-5],
        [-1,0,-2],
        [3,-4,1]
    ], dtype=np.float64)

In [11]:
from numpy.linalg import det, inv

In [12]:
def inverse(x: np.ndarray):
    if x.ndim != 2:
        return None

    a = np.zeros(x.shape)
    n = x.shape[0]
    for i in range(n):
        for j in range(n):
            mask = np.array([
                    [i != i0 and j != j0 for j0 in range(n)] 
                    for i0 in range(n)
                ])
            m = x[mask].reshape(n-1,n-1)
            a[i][j] = (-1)**(i+j+2) * det(m)

    return a.T / det(x)

In [13]:
inverse(x)

array([[ 1.33333333, -3.        ,  0.66666667],
       [ 0.83333333, -2.        ,  0.16666667],
       [-0.66666667,  1.        , -0.33333333]])

In [14]:
inv(x)

array([[ 1.33333333, -3.        ,  0.66666667],
       [ 0.83333333, -2.        ,  0.16666667],
       [-0.66666667,  1.        , -0.33333333]])

4. Extract specific rows and columns using Slicing

In [15]:
x[1] # extracts the 2nd row

array([-1.,  0., -2.])

In [16]:
x[:,1] # extracts the 2nd column

array([ 2.,  0., -4.])

5. Import data from files directly into ndarray using the loadtxt function.

In [17]:
x = np.eye(3)

In [18]:
np.savetxt('eye.txt',x,delimiter=',')

In [20]:
# to loadtxt use the np.loadtxt
y = np.loadtxt('eye.txt',delimiter=',')
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])