In [1]:
import numpy as np

In [2]:
arr = np.array([3,4,-2,5,1,-5,25,-6,9])

1. arrange and reshape

In [3]:
arr.shape

(9,)

In [4]:
np.sort(arr)

array([-6, -5, -2,  1,  3,  4,  5,  9, 25])

In [5]:
arr.shape = 3,3

In [6]:
arr

array([[ 3,  4, -2],
       [ 5,  1, -5],
       [25, -6,  9]])

In [10]:
np.sort(arr, axis=0) # sort it along rows

array([[ 3, -6, -5],
       [ 5,  1, -2],
       [25,  4,  9]])

2. Perform unary functions

In [11]:
np.abs(arr)

array([[ 3,  4,  2],
       [ 5,  1,  5],
       [25,  6,  9]])

In [13]:
np.sqrt(np.abs(arr)) # NOTE: -ve values lead to nan (not a number)

array([[1.73205081, 2.        , 1.41421356],
       [2.23606798, 1.        , 2.23606798],
       [5.        , 2.44948974, 3.        ]])

In [14]:
np.exp(arr)

array([[2.00855369e+01, 5.45981500e+01, 1.35335283e-01],
       [1.48413159e+02, 2.71828183e+00, 6.73794700e-03],
       [7.20048993e+10, 2.47875218e-03, 8.10308393e+03]])

In [15]:
np.square(arr)

array([[  9,  16,   4],
       [ 25,   1,  25],
       [625,  36,  81]])

In [16]:
np.sin(arr)

array([[ 0.14112001, -0.7568025 , -0.90929743],
       [-0.95892427,  0.84147098,  0.95892427],
       [-0.13235175,  0.2794155 ,  0.41211849]])

In [17]:
np.cos(arr)

array([[-0.9899925 , -0.65364362, -0.41614684],
       [ 0.28366219,  0.54030231,  0.28366219],
       [ 0.99120281,  0.96017029, -0.91113026]])

In [18]:
np.tan(arr)

array([[-0.14254654,  1.15782128,  2.18503986],
       [-3.38051501,  1.55740772,  3.38051501],
       [-0.13352641,  0.29100619, -0.45231566]])